# Generated by Django 6.0.7 on 2026-09-02 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this key is for, so it can be revoked knowingly.', max_length=100)),
                ('hashed', models.CharField(db_index=True, max_length=64, unique=True)),
                ('hint', models.CharField(help_text='The start of the key, to tell it from another in a list.', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Past this, the key stops working. Blank never expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='Everything this key may do, it does as this person.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'ordering': ['name'],
            },
        ),
    ]
