# Generated by Django 6.0.7 on 2026-08-30 17:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plinta_datasources', '0003_datasourcefield_renderer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, validators=[django.core.validators.RegexValidator(message='Must start with a lowercase letter and contain only lowercase letters, numbers, hyphens and underscores.', regex='^[a-z][a-z0-9_-]*$')])),
                ('component_type', models.CharField(help_text='A registered component. An unregistered one renders an empty slot.', max_length=50)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Validated against the component's schema when saved.")),
                ('base_filter', models.JSONField(blank=True, default=dict, help_text='Locked filter values, always applied and invisible to the viewer. Placeholders resolve.')),
                ('queryset_modifier', models.CharField(blank=True, default='', help_text="A registered queryset modifier's name. Not an import path.", max_length=50)),
                ('mode', models.CharField(blank=True, choices=[('', 'Component default'), ('inline', 'Inline'), ('fetch', 'Fetch')], default='', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('data_source', models.ForeignKey(help_text='A block cannot exist without the model it reads.', on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='plinta_datasources.datasource')),
                ('owner', models.ForeignKey(blank=True, help_text='Null is public.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text="The delta. Merged over the block's config when rendering.")),
                ('is_default', models.BooleanField(default=False, help_text='Applied when this viewer opens the block.')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to='plinta_blocks.block')),
                ('owner', models.ForeignKey(blank=True, help_text='Null is public.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_block_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name',), name='unique_public_block_name'),
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(fields=('block', 'owner', 'name'), name='unique_view_name_per_block_and_owner'),
        ),
        migrations.AddConstraint(
            model_name='savedview',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('block', 'name'), name='unique_public_view_name_per_block'),
        ),
    ]
