# Generated by Django 6.0.7 on 2026-08-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_blocks', '0001_initial'),
        ('plinta_datasources', '0003_datasourcefield_renderer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Required by a component that reads a model. A content component such as text carries its own content in config.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='plinta_datasources.datasource'),
        ),
    ]
