# Generated by Django 6.0.7 on 2026-08-30 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plinta_blocks', '0001_initial'),
        ('plinta_datasources', '0003_datasourcefield_renderer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='plinta_pages.menusection')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('page_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('detail', 'Detail'), ('custom-template', 'Custom template')], default='dashboard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('menu_order', models.PositiveIntegerField(default=0)),
                ('menu_icon', models.CharField(blank=True, default='', max_length=50)),
                ('template_name', models.CharField(blank=True, default='', help_text='How a custom-template page resolves. A path plinta or a consumer ships, not authored content.', max_length=200)),
                ('context_param', models.CharField(blank=True, default='', help_text='The URL parameter a detail page binds its record to.', max_length=50)),
                ('tabs', models.JSONField(blank=True, default=list, help_text='Nav tabs above the blocks. The active tab reaches blocks as a request parameter.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Page-level settings for a contrib package, under its own key. Core never inspects them.')),
                ('menu_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='plinta_pages.menugroup')),
                ('owner', models.ForeignKey(blank=True, help_text='Null is public.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('primary_data_source', models.ForeignKey(blank=True, help_text='The model a detail page shows.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail_pages', to='plinta_datasources.datasource')),
            ],
            options={
                'ordering': ['menu_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('values', models.JSONField(blank=True, default=dict, help_text='Filter values. Placeholders are stored as written and resolve at query time.')),
                ('is_default', models.BooleanField(default=False, help_text='Applied when a viewer has set no filters. Their own default wins over a public one.')),
                ('owner', models.ForeignKey(blank=True, help_text='Null is public.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_sets', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_sets', to='plinta_pages.page')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text="Shown instead of the block's own name. Blank uses it.", max_length=200)),
                ('column', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('height', models.CharField(blank=True, default='', help_text='CSS length. Blank lets the block decide.', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('context_filter', models.JSONField(blank=True, default=dict, help_text='Extra filter values for this placement only. Placeholders resolve.')),
                ('tab', models.CharField(blank=True, default='', help_text='Which tab shows this placement. Blank shows it on all.', max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='plinta_blocks.block')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='plinta_pages.page')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Field path the control filters on.', max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('widget', models.CharField(choices=[('input', 'Text input'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('daterange', 'Date range'), ('boolean', 'Yes / no')], default='input', max_length=20)),
                ('lookup', models.CharField(choices=[('exact', 'Exact'), ('in', 'One of'), ('range', 'Between'), ('icontains', 'Contains')], default='exact', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('default_value', models.JSONField(blank=True, default=None, help_text='Applied when the viewer has set nothing. Placeholders resolve.', null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='plinta_pages.page')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PageFilterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_preferences', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_preferences', to='plinta_pages.page')),
            ],
        ),
        migrations.AddConstraint(
            model_name='menugroup',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='unique_group_per_section'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_page_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='unique_public_page_slug'),
        ),
        migrations.AddConstraint(
            model_name='filterset',
            constraint=models.UniqueConstraint(fields=('page', 'owner', 'name'), name='unique_filterset_name_per_page_and_owner'),
        ),
        migrations.AddConstraint(
            model_name='filterset',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('page', 'name'), name='unique_public_filterset_name_per_page'),
        ),
        migrations.AddConstraint(
            model_name='pagefilter',
            constraint=models.UniqueConstraint(fields=('page', 'field_name'), name='unique_filter_per_page'),
        ),
        migrations.AddConstraint(
            model_name='pagefilterpreference',
            constraint=models.UniqueConstraint(fields=('page', 'owner'), name='unique_preference_per_page_and_owner'),
        ),
    ]
