# Generated by Django 6.0.7 on 2026-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefilter',
            name='widget',
            field=models.CharField(default='input', help_text='A registered filter widget. An unregistered one draws as a text input.', max_length=50),
        ),
    ]
