# Generated by Django 6.0.7 on 2026-08-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0003_datasourcefield_renderer'),
        ('plinta_pages', '0002_alter_pagefilter_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefilter',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='Needed only by a widget that offers options to choose from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_filters', to='plinta_datasources.datasource'),
        ),
    ]
