# Generated by Django 6.0.7 on 2026-08-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_pages', '0004_rename_filter_widgets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagefilter',
            name='widget',
            field=models.CharField(default='input_plinta', help_text='A registered filter widget. An unregistered one draws as a text input.', max_length=50),
        ),
    ]
