# Generated by Django 6.0.7 on 2026-08-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_pages', '0005_alter_pagefilter_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefilter',
            name='allowed_lookups',
            field=models.JSONField(blank=True, default=list, help_text='Operators the viewer may pick from. Empty means the one above, fixed.'),
        ),
        migrations.AlterField(
            model_name='pagefilter',
            name='lookup',
            field=models.CharField(choices=[('exact', 'is'), ('iexact', 'is (any case)'), ('icontains', 'contains'), ('istartswith', 'starts with'), ('iendswith', 'ends with'), ('in', 'one of'), ('gt', 'greater than'), ('gte', 'at least'), ('lt', 'less than'), ('lte', 'at most'), ('range', 'between'), ('isnull', 'is empty')], default='exact', max_length=20),
        ),
    ]
