# Generated by Django 6.0.7 on 2026-08-31 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_pages', '0006_pagefilter_allowed_lookups_alter_pagefilter_lookup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugroup',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='plinta_pages.menusection'),
        ),
        migrations.AddConstraint(
            model_name='menugroup',
            constraint=models.UniqueConstraint(condition=models.Q(('section__isnull', True)), fields=('name',), name='unique_group_without_section'),
        ),
    ]
