# Generated by Django 6.0.7 on 2026-08-31 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_blocks', '0002_alter_block_data_source'),
        ('plinta_pages', '0007_alter_menugroup_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageblock',
            name='default_view',
            field=models.ForeignKey(blank=True, help_text="The view this placement opens on. Blank uses the viewer's own default, then a public one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='plinta_blocks.savedview'),
        ),
    ]
