# Generated by Django 6.1.1 on 2026-09-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_pages', '0008_pageblock_default_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='config',
        ),
        migrations.RemoveField(
            model_name='page',
            name='context_param',
        ),
    ]
