# Generated by Django 6.0.7 on 2026-08-30 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('state_changed', 'State changed')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(blank=True, default='', max_length=60)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{field: [before, after]}, as the event carried it.')),
                ('actor', models.ForeignKey(blank=True, help_text='Null when nothing was signed in — an importer, a command.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-at', '-pk'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='plinta_audi_content_312369_idx')],
            },
        ),
    ]
