# Generated by Django 6.0.7 on 2026-08-30 23:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Must start with a lowercase letter and contain only lowercase letters, numbers and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('state_field', models.CharField(default='state', help_text="The model's own field holding the state code. A plain column, so it sorts and filters like any other.", max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(help_text='The model this workflow governs.', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Must start with a lowercase letter and contain only lowercase letters, numbers and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('label', models.CharField(max_length=100)),
                ('colour', models.CharField(blank=True, default='', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_initial', models.BooleanField(default=False, help_text='Where a row starts when it has no state.')),
                ('is_final', models.BooleanField(default=False, help_text='Nothing leaves this state.')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='plinta_workflow.workflow')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text="The button's words.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('guard', models.CharField(blank=True, default='', help_text="A registered guard's name. Unset means the permission and the row policy decide alone.", max_length=60)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='plinta_workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='plinta_workflow.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='plinta_workflow.workflow')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('workflow', 'code'), name='unique_state_code_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('workflow', 'from_state', 'to_state'), name='unique_transition_per_pair'),
        ),
    ]
