# Generated by Django 6.0.7 on 2026-08-30 12:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Identifier used in configuration, e.g. 'purchase_orders'.", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Must start with a lowercase letter and contain only lowercase letters, numbers and underscores.', regex='^[a-z][a-z0-9_]*$')])),
                ('label', models.CharField(help_text="Shown to people, e.g. 'Purchase Orders'.", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_api', models.BooleanField(default=False, help_text='Publish as a resource on the public API. Curation, not access control — permissions decide what a caller may read either way.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.OneToOneField(help_text='The Django model this represents. One DataSource per model.', on_delete=django.db.models.deletion.PROTECT, related_name='datasource', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'data source',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Field path on the model. May traverse, e.g. 'region__name'.", max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True, help_text='Shown by default.')),
                ('format', models.CharField(blank=True, choices=[('', 'None'), ('currency', 'Currency'), ('percent', 'Percent'), ('date', 'Date'), ('datetime', 'Date and time'), ('number', 'Number'), ('textarea', 'Long text'), ('html', 'HTML')], default='', max_length=20)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Fixed pixel width. Unset lets the widget decide.', null=True)),
                ('decimals', models.PositiveSmallIntegerField(blank=True, help_text='Decimal places. Honoured by every renderer.', null=True)),
                ('thousands_separator', models.BooleanField(default=False)),
                ('sorter', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('date', 'Date')], default='string', max_length=10)),
                ('header_filter', models.CharField(blank=True, choices=[('', 'None'), ('input', 'Text input'), ('select', 'Select')], default='', max_length=10)),
                ('filterable', models.BooleanField(default=False, help_text="Offered as a control on a page's filter bar.")),
                ('filter_widget', models.CharField(blank=True, choices=[('', 'None'), ('multiselect', 'Multi-select'), ('daterange', 'Date range')], default='', max_length=20)),
                ('filter_lookup', models.CharField(choices=[('exact', 'Exact'), ('in', 'One of'), ('range', 'Between')], default='exact', max_length=10)),
                ('filter_display_format', models.CharField(blank=True, default='', help_text="Template for a filter's option labels, e.g. '{state__name}'.", max_length=200)),
                ('editable', models.BooleanField(default=False, help_text='Mints a change permission for this column.')),
                ('picker_mode', models.CharField(choices=[('auto', 'Automatic'), ('list', 'Full list'), ('search', 'Search as you type')], default='auto', help_text="How a related field offers its choices. 'auto' picks a list under a hundred rows and a search above.", max_length=10)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='plinta_datasources.datasource')),
            ],
            options={
                'verbose_name': 'data source field',
                'ordering': ['order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('data_source', 'field_name'), name='unique_field_per_datasource')],
            },
        ),
    ]
