# Generated by Django 6.0.7 on 2026-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefield',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text="Drawn before the value, e.g. '$'. Replaces whatever the format would have drawn.", max_length=8),
        ),
        migrations.AddField(
            model_name='datasourcefield',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text="Drawn after the value, e.g. 'kg' or '%'.", max_length=8),
        ),
    ]
