# Generated by Django 6.0.7 on 2026-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefield',
            name='currency',
            field=models.CharField(blank=True, default='', help_text="ISO code for a currency column, e.g. 'USD'. Core prefixes it; converting it or showing a symbol is a field renderer's job.", max_length=3),
        ),
    ]
