# Generated by Django 6.0.7 on 2026-08-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0002_datasourcefield_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefield',
            name='prefix',
            field=models.CharField(blank=True, default='', help_text="Drawn before the value, e.g. '$'. Replaces whatever the format would have drawn.", max_length=8),
        ),
        migrations.AddField(
            model_name='datasourcefield',
            name='suffix',
            field=models.CharField(blank=True, default='', help_text="Drawn after the value, e.g. 'kg' or '%'.", max_length=8),
        ),
        migrations.AlterField(
            model_name='datasourcefield',
            name='currency',
            field=models.CharField(blank=True, default='', help_text="ISO code for a currency column, e.g. 'USD'. Semantic, not display: it says what the numbers are denominated in, so conversion knows. Use 'prefix' to draw a symbol.", max_length=3),
        ),
    ]
