# Generated by Django 6.0.7 on 2026-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0002_display_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcefield',
            name='renderer',
            field=models.CharField(blank=True, default='', help_text='A registered field renderer to draw this column with. Unset formats the value.', max_length=50),
        ),
    ]
