# Generated by Django 6.0.7 on 2026-08-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0003_datasourcefield_renderer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasourcefield',
            name='filter_display_format',
        ),
        migrations.RemoveField(
            model_name='datasourcefield',
            name='filter_lookup',
        ),
        migrations.RemoveField(
            model_name='datasourcefield',
            name='filter_widget',
        ),
    ]
