# Generated by Django 6.0.7 on 2026-09-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinta_datasources', '0004_remove_datasourcefield_filter_display_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcefield',
            name='filterable',
            field=models.BooleanField(default=False, help_text="Offers a filter in a widget's own column header. Not the page's filter bar — a PageFilter row is that decision, and it may name a path that is not a column at all."),
        ),
    ]
